/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2011
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/****************************************************************************
 *
 * COMPONENT:   ASN
 * MODULE:      ASN_MEMORY
 * DESCRIPTION: Auto generated by MTK ASN.1 Compiler
 *
 ****************************************************************************/
/*****************************************************************************
 * $Log:$
 * 
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * for msbb2
 *
 * removed!
 * removed!
 * for msbb2
 *
 ****************************************************************************/
#include "kal_public_api.h"
//#include "app_buff_alloc.h"
#include "asn_memory.h"
#include "asn_common.h"

unsigned int max_size_tolerance=0;

extern void asnMemSetMaxSizeTolerance(unsigned int maxlength)
{
   if (maxlength > max_size_tolerance)
      max_size_tolerance = maxlength;
}

extern unsigned int asnMemGetMaxSizeTolerance(void)
{
   return max_size_tolerance;
}

extern  void  asnMemAlloc(void *pVoid, void ** ppBuffer, unsigned long size)
{
   /**
    * For MCDDLL, malloc() from C Standard Library is used;
    * otherwise, memory allocation from KAL is used.
    */
	AsnContext *pContext = (AsnContext*) pVoid;
    if(size == 0)
    {
      *ppBuffer = (void *)0;
      return;
    }

    /*added for memory limit*/
    if(max_size_tolerance > 0)
    {
        if(size > max_size_tolerance)
        {
            UA1_ERROR(16);
        }
    }

    if (pContext->pMemAllocFunc != NULL)
    {
        pContext->pMemAllocFunc(ppBuffer, size, __FILE__, __LINE__);
    }
    else
    {
#ifdef  MCD_DLL_EXPORT
        *ppBuffer = (void *)malloc(size);
        memset(*ppBuffer ,0,size);
#else
        *ppBuffer = (void*) get_ctrl_buffer(size);
#endif 
        if(*ppBuffer == NULL)
        {
            ASSERT(0);
        }
    }
}

extern  void  asnMemFree(void ** ppBuffer)
{
   /**
    * For MCDDLL, malloc() from C Standard Library is used;
    * otherwise, memory allocation from KAL is used.
    */
    if(NULL == *ppBuffer)
       return;
#ifdef  MCD_DLL_EXPORT
    free(*ppBuffer);
#else
    free_ctrl_buffer(*ppBuffer);
#endif
    *ppBuffer = NULL;
}


extern  void  asnMemMove(void * pDest, const void * pSource, unsigned long uLen)
{
	memmove(pDest, pSource, uLen);
}

extern  void  asnMemCopy(void * pDest, const void * pSource, unsigned long uLen)
{
#ifdef  MCD_DLL_EXPORT
   memcpy(pDest, pSource, (signed)uLen);
#else
   kal_mem_cpy (pDest, pSource, (signed)uLen);
#endif
}

extern long asnMemCmp(void *p1, void *p2, unsigned long uLen)
{
	return memcmp(p1, p2, uLen);
}

extern void asnMemSet(void *p1, unsigned long value, unsigned long uLen)
{
	memset(p1, value, uLen);
}
