#ifndef MD_MW_SAP_H
#define MD_MW_SAP_H

#include "sap_range.h"

MODULE_SAP_BEGIN(SAP_ID_MD_MW_CODE_BEGIN)
	CSM_VT_SAP,
	DATA_MPAL_SAP,
	EXTMODEM_PPP_SAP,
	FT_FTA_SAP,
	FT_FTC_SAP,
	FTA_FT_SAP,
	FTC_FT_SAP,
	GPS_LCSP_SAP,
	L2R_PPP_SAP,
	NDIS_RATDM_SAP,
	PPP_L4C_SAP,
	RABM_NDIS_SAP,
	RABM_PPP_SAP,
	RABM_TCPIP_SAP,
	RATDM_PPP_SAP,
	RATDM_TCPIP_SAP, 
	SMSAL_SOC_SAP,
	SNDCP_PPP_SAP,
	PPP_RAT_TCM_SAP,
	TCM_TCPIP_SAP,
	TDT_PPP_SAP,
	UPS_SAP,
	VT_CSR_SAP,
	VT_F_CSR_SAP,
	VT_L4C_SAP,
	VT_SAP,
MODULE_SAP_END(SAP_ID_MD_MW_CODE_TAIL)

#endif // MD_MW_SAP_H 
