#ifndef MD_MMI_SAP_H
#define MD_MMI_SAP_H

#include "sap_range.h"

MODULE_SAP_BEGIN(SAP_ID_MD_MMI_CODE_BEGIN)
	MMI_AS_SAP = SAP_ID_MD_MMI_CODE_BEGIN,
	MMI_L4C_SAP,
MODULE_SAP_END(SAP_ID_MD_MMI_CODE_TAIL)

#endif /* MD_MMI_SAP_H */
