#ifndef MODULE_MSG_RANGE_H
#define MODULE_MSG_RANGE_H

typedef enum {
    MSG_ID_XXX_CODE_BASE = 500,
    
    MSG_ID_SYSDEBUG_CODE_BEGIN, MSG_ID_SYSDEBUG_CODE_TAIL = MSG_ID_SYSDEBUG_CODE_BEGIN + 100,
    
    MSG_ID_CC_CODE_BEGIN, MSG_ID_CC_CODE_TAIL = MSG_ID_CC_CODE_BEGIN + 100,
    
    MSG_ID_CISS_CODE_BEGIN, MSG_ID_CISS_CODE_TAIL = MSG_ID_CISS_CODE_BEGIN + 150,

	MSG_ID_MM_CODE_BEGIN, MSG_ID_MM_CODE_TAIL = MSG_ID_MM_CODE_BEGIN + 200,
    
    MSG_ID_SMS_CODE_BEGIN, MSG_ID_SMS_CODE_TAIL = MSG_ID_SMS_CODE_BEGIN + 100,
    
    MSG_ID_SIM_PUBLIC_CODE_BEGIN, MSG_ID_SIM_PUBLIC_CODE_TAIL = MSG_ID_SIM_PUBLIC_CODE_BEGIN + 50,
    
    MSG_ID_SIM_PS_CODE_BEGIN, MSG_ID_SIM_PS_CODE_TAIL = MSG_ID_SIM_PS_CODE_BEGIN + 200,
    
    MSG_ID_L4_PUBLIC_CODE_BEGIN, MSG_ID_L4_PUBLIC_CODE_TAIL = MSG_ID_L4_PUBLIC_CODE_BEGIN + 100,
    
    MSG_ID_L4C_CODE_BEGIN, MSG_ID_L4C_CODE_TAIL = MSG_ID_L4C_CODE_BEGIN + 600,

    MSG_ID_RAT_TCM_CODE_BEGIN, MSG_ID_RAT_TCM_CODE_TAIL = MSG_ID_RAT_TCM_CODE_BEGIN + 200,
    
    MSG_ID_TCM_CODE_BEGIN, MSG_ID_TCM_CODE_TAIL = MSG_ID_TCM_CODE_BEGIN + 200,

    MSG_ID_CSM_CODE_BEGIN, MSG_ID_CSM_CODE_TAIL = MSG_ID_CSM_CODE_BEGIN + 120,

    MSG_ID_SMSAL_CODE_BEGIN, MSG_ID_SMSAL_CODE_TAIL = MSG_ID_SMSAL_CODE_BEGIN + 150,
    
    MSG_ID_SMU_CODE_BEGIN, MSG_ID_SMU_CODE_TAIL = MSG_ID_SMU_CODE_BEGIN + 100,
    
    MSG_ID_UEM_CODE_BEGIN, MSG_ID_UEM_CODE_TAIL = MSG_ID_UEM_CODE_BEGIN + 150,
    
    MSG_ID_RAC_CODE_BEGIN, MSG_ID_RAC_CODE_TAIL = MSG_ID_RAC_CODE_BEGIN + 200,
    
    MSG_ID_USAT_CODE_BEGIN, MSG_ID_USAT_CODE_TAIL = MSG_ID_USAT_CODE_BEGIN + 100,
    
    MSG_ID_PHB_CODE_BEGIN, MSG_ID_PHB_CODE_TAIL = MSG_ID_PHB_CODE_BEGIN + 150,
    
    MSG_ID_PS_CODE_BEGIN, MSG_ID_PS_CODE_TAIL = MSG_ID_PS_CODE_BEGIN + 150,

    MSG_ID_MBCI_CODE_BEGIN, MSG_ID_MBCI_CODE_TAIL = MSG_ID_MBCI_CODE_BEGIN + 20,
    
    MSG_ID_ATCI_CODE_BEGIN, MSG_ID_ATCI_CODE_TAIL = MSG_ID_ATCI_CODE_BEGIN + 150,
    
    MSG_ID_ENG_CODE_BEGIN, MSG_ID_ENG_CODE_TAIL = MSG_ID_ENG_CODE_BEGIN + 150,

    MSG_ID_PSDM_CODE_BEGIN, MSG_ID_PSDM_CODE_TAIL = MSG_ID_PSDM_CODE_BEGIN + 30,
    
    MSG_ID_VMMI_CODE_BEGIN, MSG_ID_VMMI_CODE_TAIL = MSG_ID_VMMI_CODE_BEGIN + 100,
    
    MSG_ID_RLC_CODE_BEGIN, MSG_ID_RLC_CODE_TAIL = MSG_ID_RLC_CODE_BEGIN + 100,

    MSG_ID_RLC_TDD_CODE_BEGIN, MSG_ID_RLC_TDD_CODE_TAIL = MSG_ID_RLC_TDD_CODE_BEGIN + 100,
    
    MSG_ID_RRM_COMMON_CODE_BEGIN, MSG_ID_RRM_COMMON_CODE_TAIL = MSG_ID_RRM_COMMON_CODE_BEGIN + 100,

    MSG_ID_RRM_COMMON_TDD_CODE_BEGIN, MSG_ID_RRM_COMMON_TDD_CODE_TAIL = MSG_ID_RRM_COMMON_TDD_CODE_BEGIN + 100,
    
    MSG_ID_RCS_CODE_BEGIN, MSG_ID_RCS_CODE_TAIL = MSG_ID_RCS_CODE_BEGIN + 100,
    
    MSG_ID_RCS_TDD_CODE_BEGIN, MSG_ID_RCS_TDD_CODE_TAIL = MSG_ID_RCS_TDD_CODE_BEGIN + 100,

    MSG_ID_RMPC_CODE_BEGIN, MSG_ID_RMPC_CODE_TAIL = MSG_ID_RMPC_CODE_BEGIN + 100,
    
    MSG_ID_RMPC_TDD_CODE_BEGIN, MSG_ID_RMPC_TDD_CODE_TAIL = MSG_ID_RMPC_TDD_CODE_BEGIN + 100,

    MSG_ID_RRM_MPAL_MM_CODE_BEGIN, MSG_ID_RRM_MPAL_MM_CODE_TAIL = MSG_ID_RRM_MPAL_MM_CODE_BEGIN + 100,
    
    MSG_ID_RRM_MPAL_MM_TDD_CODE_BEGIN, MSG_ID_RRM_MPAL_MM_TDD_CODE_TAIL = MSG_ID_RRM_MPAL_MM_TDD_CODE_BEGIN + 100,

    MSG_ID_MAC_CODE_BEGIN, MSG_ID_MAC_CODE_TAIL = MSG_ID_MAC_CODE_BEGIN + 100,
    
    MSG_ID_MAC_TDD_CODE_BEGIN, MSG_ID_MAC_TDD_CODE_TAIL = MSG_ID_MAC_TDD_CODE_BEGIN + 100,

    MSG_ID_LAPDM_CODE_BEGIN, MSG_ID_LAPDM_CODE_TAIL = MSG_ID_LAPDM_CODE_BEGIN + 100,
    
    MSG_ID_LAPDM_TDD_CODE_BEGIN, MSG_ID_LAPDM_TDD_CODE_TAIL = MSG_ID_LAPDM_TDD_CODE_BEGIN + 100,

    MSG_ID_REASM_CODE_BEGIN, MSG_ID_REASM_CODE_TAIL = MSG_ID_REASM_CODE_BEGIN + 100,
    
    MSG_ID_REASM_TDD_CODE_BEGIN, MSG_ID_REASM_TDD_CODE_TAIL = MSG_ID_REASM_TDD_CODE_BEGIN + 100,

    MSG_ID_MPAL_CODE_BEGIN, MSG_ID_MPAL_CODE_TAIL = MSG_ID_MPAL_CODE_BEGIN + 100,
    
    MSG_ID_MPAL_TDD_CODE_BEGIN, MSG_ID_MPAL_TDD_CODE_TAIL = MSG_ID_MPAL_TDD_CODE_BEGIN + 100,
    
    MSG_ID_LLC_CODE_BEGIN, MSG_ID_LLC_CODE_TAIL = MSG_ID_LLC_CODE_BEGIN + 100,
    
    MSG_ID_P2P_CODE_BEGIN, MSG_ID_P2P_CODE_TAIL = MSG_ID_P2P_CODE_BEGIN + 100,
    
    MSG_ID_SND_CODE_BEGIN, MSG_ID_SND_CODE_TAIL = MSG_ID_SND_CODE_BEGIN + 100,
    
    MSG_ID_SM_CODE_BEGIN, MSG_ID_SM_CODE_TAIL = MSG_ID_SM_CODE_BEGIN + 100,
    
    MSG_ID_TDT_CODE_BEGIN, MSG_ID_TDT_CODE_TAIL = MSG_ID_TDT_CODE_BEGIN + 100,
    
    MSG_ID_T30_CODE_BEGIN, MSG_ID_T30_CODE_TAIL = MSG_ID_T30_CODE_BEGIN + 50,
    
    MSG_ID_FA_CODE_BEGIN, MSG_ID_FA_CODE_TAIL = MSG_ID_FA_CODE_BEGIN + 50,
    
    MSG_ID_L2R_CODE_BEGIN, MSG_ID_L2R_CODE_TAIL = MSG_ID_L2R_CODE_BEGIN + 100,
    
    MSG_ID_RLP_CODE_BEGIN, MSG_ID_RLP_CODE_TAIL = MSG_ID_RLP_CODE_BEGIN + 100,
    
    MSG_ID_PS_PUBLIC_VT_MSG_CODE_BEGIN, MSG_ID_PS_PUBLIC_VT_MSG_CODE_TAIL = MSG_ID_PS_PUBLIC_VT_MSG_CODE_BEGIN + 30,
    
    MSG_ID_VT_CODE_BEGIN, MSG_ID_VT_CODE_TAIL = MSG_ID_VT_CODE_BEGIN + 70,    
    
    MSG_ID_NVRAM_CODE_BEGIN, MSG_ID_NVRAM_CODE_TAIL = MSG_ID_NVRAM_CODE_BEGIN + 100,
    
    MSG_ID_L1_CODE_BEGIN, MSG_ID_L1_CODE_TAIL = MSG_ID_L1_CODE_BEGIN + 300,
       
    MSG_ID_HAL_L1_CODE_BEGIN, MSG_ID_HAL_L1_CODE_TAIL = MSG_ID_HAL_L1_CODE_BEGIN + 40,
    
    MSG_ID_L1HISR_CODE_BEGIN, MSG_ID_L1HISR_CODE_TAIL = MSG_ID_L1HISR_CODE_BEGIN + 40,    
    
    MSG_ID_FT_CODE_BEGIN, MSG_ID_FT_CODE_TAIL = MSG_ID_FT_CODE_BEGIN + 100,
    
    MSG_ID_TST_CODE_BEGIN, MSG_ID_TST_CODE_TAIL = MSG_ID_TST_CODE_BEGIN + 1200,    
    
    MSG_ID_AUDIO_MSG_CODE_BEGIN, MSG_ID_AUDIO_MSG_CODE_TAIL = MSG_ID_AUDIO_MSG_CODE_BEGIN + 100,
    
    MSG_ID_RATCM_CODE_BEGIN, MSG_ID_RATCM_CODE_TAIL = MSG_ID_RATCM_CODE_BEGIN + 300,
    
    MSG_ID_RATDM_CODE_BEGIN, MSG_ID_RATDM_CODE_TAIL = MSG_ID_RATDM_CODE_BEGIN + 100,
    
    MSG_ID_ADR_CODE_BEGIN, MSG_ID_ADR_CODE_TAIL = MSG_ID_ADR_CODE_BEGIN + 20,
    
    MSG_ID_CSCE_CODE_BEGIN, MSG_ID_CSCE_CODE_TAIL = MSG_ID_CSCE_CODE_BEGIN + 100,
    
    MSG_ID_CSE_CODE_BEGIN, MSG_ID_CSE_CODE_TAIL = MSG_ID_CSE_CODE_BEGIN + 100,
    
    MSG_ID_MEME_CODE_BEGIN, MSG_ID_MEME_CODE_TAIL = MSG_ID_MEME_CODE_BEGIN + 100,
    
    MSG_ID_RRCE_CODE_BEGIN, MSG_ID_RRCE_CODE_TAIL = MSG_ID_RRCE_CODE_BEGIN + 100,
     
    MSG_ID_SIBE_CODE_BEGIN, MSG_ID_SIBE_CODE_TAIL = MSG_ID_SIBE_CODE_BEGIN + 100,
    
    MSG_ID_SLCE_CODE_BEGIN, MSG_ID_SLCE_CODE_TAIL = MSG_ID_SLCE_CODE_BEGIN + 200,
     
    MSG_ID_DBME_CODE_BEGIN, MSG_ID_DBME_CODE_TAIL = MSG_ID_DBME_CODE_BEGIN + 20,

	MSG_ID_USIME_CODE_BEGIN, MSG_ID_USIME_CODE_TAIL = MSG_ID_USIME_CODE_BEGIN + 100,
	
    MSG_ID_URR_CODE_BEGIN, MSG_ID_URR_CODE_TAIL = MSG_ID_URR_CODE_BEGIN + 50,
    
    MSG_ID_ADR_TDD_CODE_BEGIN, MSG_ID_ADR_TDD_CODE_TAIL = MSG_ID_ADR_TDD_CODE_BEGIN + 20,

    MSG_ID_CSCE_TDD_CODE_BEGIN, MSG_ID_CSCE_TDD_CODE_TAIL = MSG_ID_CSCE_TDD_CODE_BEGIN + 100,

    MSG_ID_CSE_TDD_CODE_BEGIN, MSG_ID_CSE_TDD_CODE_TAIL = MSG_ID_CSE_TDD_CODE_BEGIN + 100,

    MSG_ID_MEME_TDD_CODE_BEGIN, MSG_ID_MEME_TDD_CODE_TAIL = MSG_ID_MEME_TDD_CODE_BEGIN + 100,
    
	MSG_ID_RRCE_TDD_CODE_BEGIN, MSG_ID_RRCE_TDD_CODE_TAIL = MSG_ID_RRCE_TDD_CODE_BEGIN + 100,

    MSG_ID_SIBE_TDD_CODE_BEGIN, MSG_ID_SIBE_TDD_CODE_TAIL = MSG_ID_SIBE_TDD_CODE_BEGIN + 100,
    
	MSG_ID_SLCE_TDD_CODE_BEGIN, MSG_ID_SLCE_TDD_CODE_TAIL = MSG_ID_SLCE_TDD_CODE_BEGIN + 200,
     
    MSG_ID_DBME_TDD_CODE_BEGIN, MSG_ID_DBME_TDD_CODE_TAIL = MSG_ID_DBME_TDD_CODE_BEGIN + 20,

    MSG_ID_USIME_TDD_CODE_BEGIN, MSG_ID_USIME_TDD_CODE_TAIL = MSG_ID_USIME_TDD_CODE_BEGIN + 100,

    MSG_ID_URR_TDD_CODE_BEGIN, MSG_ID_URR_TDD_CODE_TAIL = MSG_ID_URR_TDD_CODE_BEGIN + 50,
   	
    MSG_ID_UMAC_CODE_BEGIN, MSG_ID_UMAC_CODE_TAIL = MSG_ID_UMAC_CODE_BEGIN + 100,
    
    MSG_ID_URLC_CODE_BEGIN, MSG_ID_URLC_CODE_TAIL = MSG_ID_URLC_CODE_BEGIN + 150,

	MSG_ID_SEQ_CODE_BEGIN, MSG_ID_SEQ_CODE_TAIL = MSG_ID_SEQ_CODE_BEGIN + 100,
    
    MSG_ID_URLC_TDD_CODE_BEGIN, MSG_ID_URLC_TDD_CODE_TAIL = MSG_ID_URLC_TDD_CODE_BEGIN + 150,

    MSG_ID_UL2_CODE_BEGIN, MSG_ID_UL2_CODE_TAIL = MSG_ID_UL2_CODE_BEGIN + 100,
    
    MSG_ID_BMC_CODE_BEGIN, MSG_ID_BMC_CODE_TAIL = MSG_ID_BMC_CODE_BEGIN + 100,
       
    MSG_ID_CSR_CODE_BEGIN, MSG_ID_CSR_CODE_TAIL = MSG_ID_CSR_CODE_BEGIN + 100,
        
    MSG_ID_DRLC_CODE_BEGIN, MSG_ID_DRLC_CODE_TAIL = MSG_ID_DRLC_CODE_BEGIN + 100,
    
    MSG_ID_PDCP_TDD_CODE_BEGIN, MSG_ID_PDCP_TDD_CODE_TAIL = MSG_ID_PDCP_TDD_CODE_BEGIN + 100,

    MSG_ID_PDCP_CODE_BEGIN, MSG_ID_PDCP_CODE_TAIL = MSG_ID_PDCP_CODE_BEGIN + 100,
 
    MSG_ID_RABM_TDD_CODE_BEGIN, MSG_ID_RABM_TDD_CODE_TAIL = MSG_ID_RABM_TDD_CODE_BEGIN + 100,

    MSG_ID_RABM_CODE_BEGIN, MSG_ID_RABM_CODE_TAIL = MSG_ID_RABM_CODE_BEGIN + 100,

	MSG_ID_BMC_TDD_CODE_BEGIN, MSG_ID_BMC_TDD_CODE_TAIL = MSG_ID_BMC_TDD_CODE_BEGIN + 100,

	MSG_ID_CSR_TDD_CODE_BEGIN, MSG_ID_CSR_TDD_CODE_TAIL = MSG_ID_CSR_TDD_CODE_BEGIN + 100,

	MSG_ID_DRLC_TDD_CODE_BEGIN, MSG_ID_DRLC_TDD_CODE_TAIL = MSG_ID_DRLC_TDD_CODE_BEGIN + 100,  
	
    MSG_ID_UL2D_TDD_CODE_BEGIN, MSG_ID_UL2D_TDD_CODE_TAIL = MSG_ID_UL2D_TDD_CODE_BEGIN + 100,
    
    MSG_ID_UL2D_CODE_BEGIN, MSG_ID_UL2D_CODE_TAIL = MSG_ID_UL2D_CODE_BEGIN + 100,
    
    MSG_ID_DM_CSCE_CODE_BEGIN, MSG_ID_DM_CSCE_CODE_TAIL = MSG_ID_DM_CSCE_CODE_BEGIN + 100,
    
    MSG_ID_UAS_GAS_CODE_BEGIN, MSG_ID_UAS_GAS_CODE_TAIL = MSG_ID_UAS_GAS_CODE_BEGIN + 100,

    MSG_ID_EAS_GAS_CODE_BEGIN, MSG_ID_EAS_GAS_CODE_TAIL = MSG_ID_EAS_GAS_CODE_BEGIN + 100,
    
    MSG_ID_DM_MEME_CODE_BEGIN, MSG_ID_DM_MEME_CODE_TAIL = MSG_ID_DM_MEME_CODE_BEGIN + 100,
    
    MSG_ID_DM_RRCE_CODE_BEGIN, MSG_ID_DM_RRCE_CODE_TAIL = MSG_ID_DM_RRCE_CODE_BEGIN + 100,
    
    MSG_ID_DM_RRCE_TDD_CODE_BEGIN, MSG_ID_DM_RRCE_TDD_CODE_TAIL = MSG_ID_DM_RRCE_TDD_CODE_BEGIN + 100,
    
    MSG_ID_GEMINI_UAS_CODE_BEGIN, MSG_ID_GEMINI_UAS_CODE_TAIL = MSG_ID_GEMINI_UAS_CODE_BEGIN + 100,
    
    MSG_ID_GEMINI_GAS_CODE_BEGIN, MSG_ID_GEMINI_GAS_CODE_TAIL = MSG_ID_GEMINI_GAS_CODE_BEGIN + 100,
    
    MSG_ID_UL1_MSG_CODE_BEGIN, MSG_ID_UL1_MSG_CODE_TAIL = MSG_ID_UL1_MSG_CODE_BEGIN + 300,
    
    MSG_ID_UL1DATA_MSG_CODE_BEGIN, MSG_ID_UL1DATA_MSG_CODE_TAIL = MSG_ID_UL1DATA_MSG_CODE_BEGIN + 20,
    
    MSG_ID_UL1HISR_MSG_CODE_BEGIN, MSG_ID_UL1HISR_MSG_CODE_TAIL = MSG_ID_UL1HISR_MSG_CODE_BEGIN + 5,
    
    MSG_ID_UL1C_MSG_CODE_BEGIN, MSG_ID_UL1C_MSG_CODE_TAIL = MSG_ID_UL1C_MSG_CODE_BEGIN + 20,
    
    MSG_ID_LL1_MSG_CODE_BEGIN, MSG_ID_LL1_MSG_CODE_TAIL = MSG_ID_LL1_MSG_CODE_BEGIN + 150,
    
    MSG_ID_UL1TST_MSG_CODE_BEGIN, MSG_ID_UL1TST_MSG_CODE_TAIL = MSG_ID_UL1TST_MSG_CODE_BEGIN + 50,
    
    MSG_ID_UAGPS_CP_CODE_BEGIN, MSG_ID_UAGPS_CP_CODE_TAIL = MSG_ID_UAGPS_CP_CODE_BEGIN + 30,
    
    MSG_ID_GPS_MSG_CODE_BEGIN, MSG_ID_GPS_MSG_CODE_TAIL = MSG_ID_GPS_MSG_CODE_BEGIN + 50,
    
    MSG_ID_TL1_MSG_CODE_BEGIN, MSG_ID_TL1_MSG_CODE_TAIL = MSG_ID_TL1_MSG_CODE_BEGIN + 200,
    
    MSG_ID_TL1DATA_AST_MSG_CODE_BEGIN, MSG_ID_TL1DATA_AST_MSG_CODE_TAIL = MSG_ID_TL1DATA_AST_MSG_CODE_BEGIN + 200,
    
    MSG_ID_TL1HISR_AST_MSG_CODE_BEGIN, MSG_ID_TL1HISR_AST_MSG_CODE_TAIL = MSG_ID_TL1HISR_AST_MSG_CODE_BEGIN + 50,
    
    MSG_ID_TL1FTA_AST_MSG_CODE_BEGIN, MSG_ID_TL1FTA_AST_MSG_CODE_TAIL = MSG_ID_TL1FTA_AST_MSG_CODE_BEGIN + 50,
    
    MSG_ID_RSVAS_CODE_BEGIN, MSG_ID_RSVAS_CODE_TAIL = MSG_ID_RSVAS_CODE_BEGIN + 100,
    
    MSG_ID_RSVAK_CODE_BEGIN, MSG_ID_RSVAK_CODE_TAIL = MSG_ID_RSVAK_CODE_BEGIN + 50,
    
    MSG_ID_RSVAU_CODE_BEGIN, MSG_ID_RSVAU_CODE_TAIL = MSG_ID_RSVAU_CODE_BEGIN + 50,
    
    MSG_ID_RSVAG_CODE_BEGIN, MSG_ID_RSVAG_CODE_TAIL = MSG_ID_RSVAG_CODE_BEGIN + 50,
    
    MSG_ID_RSVAE_CODE_BEGIN, MSG_ID_RSVAE_CODE_TAIL = MSG_ID_RSVAE_CODE_BEGIN + 50,
    
    MSG_ID_NDIS_MSG_CODE_BEGIN, MSG_ID_NDIS_MSG_CODE_TAIL = MSG_ID_NDIS_MSG_CODE_BEGIN + 20,
    
    MSG_ID_UPS_PUBLIC_CODE_BEGIN, MSG_ID_UPS_PUBLIC_CODE_TAIL = MSG_ID_UPS_PUBLIC_CODE_BEGIN + 20,
    
    MSG_ID_UPS_MSG_CODE_BEGIN, MSG_ID_UPS_MSG_CODE_TAIL = MSG_ID_UPS_MSG_CODE_BEGIN + 100,
    
    MSG_ID_PS_PUBLIC_SUPL_MSG_CODE_BEGIN, MSG_ID_PS_PUBLIC_SUPL_MSG_CODE_TAIL = MSG_ID_PS_PUBLIC_SUPL_MSG_CODE_BEGIN + 30,
    
    MSG_ID_SUPL_MSG_CODE_BEGIN, MSG_ID_SUPL_MSG_CODE_TAIL = MSG_ID_SUPL_MSG_CODE_BEGIN + 20,
    
    MSG_ID_CMUX_CODE_BEGIN, MSG_ID_CMUX_CODE_TAIL = MSG_ID_CMUX_CODE_BEGIN + 100,
    
    MSG_ID_PPP_CODE_BEGIN, MSG_ID_PPP_CODE_TAIL = MSG_ID_PPP_CODE_BEGIN + 100,
    
    MSG_ID_EXT_MODEM_CODE_BEGIN, MSG_ID_EXT_MODEM_CODE_TAIL = MSG_ID_EXT_MODEM_CODE_BEGIN + 50,
    
    MSG_ID_WMT_MSG_CODE_BEGIN, MSG_ID_WMT_MSG_CODE_TAIL = MSG_ID_WMT_MSG_CODE_BEGIN + 100,

    MSG_ID_EM_CODE_BEGIN, MSG_ID_EM_CODE_TAIL = MSG_ID_EM_CODE_BEGIN + 300,
    
    MSG_ID_HOSTAP_MSG_CODE_BEGIN, MSG_ID_HOSTAP_MSG_CODE_TAIL = MSG_ID_HOSTAP_MSG_CODE_BEGIN + 100,
    
    MSG_ID_FS_CODE_BEGIN, MSG_ID_FS_CODE_TAIL = MSG_ID_FS_CODE_BEGIN + 60,

    MSG_ID_MED_CODE_BEGIN, MSG_ID_MED_CODE_TAIL = MSG_ID_MED_CODE_BEGIN + 100,
    
    MSG_ID_DPS_CODE_BEGIN, MSG_ID_DPS_CODE_TAIL = MSG_ID_DPS_CODE_BEGIN + 150,
    
    MSG_ID_UDPS_CODE_BEGIN, MSG_ID_UDPS_CODE_TAIL = MSG_ID_UDPS_CODE_BEGIN + 1000,
    
    MSG_ID_DRIVER_CODE_BEGIN, MSG_ID_DRIVER_CODE_TAIL = MSG_ID_DRIVER_CODE_BEGIN + 1000,
    
    MSG_ID_MEUT_MSG_CODE_BEGIN, MSG_ID_MEUT_MSG_CODE_TAIL = MSG_ID_MEUT_MSG_CODE_BEGIN + 500,

	MSG_ID_L1_EXT_CODE_BEGIN,MSG_ID_L1_EXT_CODE_TAIL = MSG_ID_L1_EXT_CODE_BEGIN + 30,

	MSG_ID_HAPLUS_MSG_CODE_BEGIN,MSG_ID_HAPLUS_MSG_CODE_TAIL = MSG_ID_HAPLUS_MSG_CODE_BEGIN + 200,

	MSG_ID_MRS_CODE_BEGIN,MSG_ID_MRS_CODE_TAIL = MSG_ID_MRS_CODE_BEGIN + 30,
	
    /* Add by LTE SS */
    MSG_ID_EL1_CODE_BEGIN, MSG_ID_EL1_CODE_TAIL = MSG_ID_EL1_CODE_BEGIN + 200,

    MSG_ID_L1EDPS_CODE_BEGIN, MSG_ID_L1EDPS_CODE_TAIL = MSG_ID_L1EDPS_CODE_BEGIN + 1000,

    MSG_ID_EDYN_CODE_BEGIN, MSG_ID_EDYN_CODE_TAIL = MSG_ID_EDYN_CODE_BEGIN + 10,

    MSG_ID_MLL1_MSG_CODE_BEGIN, MSG_ID_MLL1_MSG_CODE_TAIL = MSG_ID_MLL1_MSG_CODE_BEGIN + 200,

    MSG_ID_EL2_CODE_BEGIN, MSG_ID_EL2_CODE_TAIL = MSG_ID_EL2_CODE_BEGIN + 100,

    MSG_ID_ERRC_CODE_BEGIN, MSG_ID_ERRC_CODE_TAIL = MSG_ID_ERRC_CODE_BEGIN + 500,

#ifdef ESIM_BUILD_CONFIG
    MSG_ID_SCRIPT_CODE_BEGIN, MSG_ID_SCRIPT_CODE_TAIL = MSG_ID_SCRIPT_CODE_BEGIN + 50,
#endif
    MSG_ID_CLDMACORE_CODE_BEGIN, MSG_ID_CLDMACORE_CODE_END = MSG_ID_CLDMACORE_CODE_BEGIN + 5,

    MSG_ID_CCIFCORE_CODE_BEGIN, MSG_ID_CCIFCORE_CODE_END = MSG_ID_CCIFCORE_CODE_BEGIN + 5,

    MSG_ID_TFTLIB_CODE_BEGIN, MSG_ID_TFTLIB_CODE_TAIL = MSG_ID_TFTLIB_CODE_BEGIN + 100,
    
    MSG_ID_NWSEL_CODE_BEGIN, MSG_ID_NWSEL_CODE_TAIL = MSG_ID_NWSEL_CODE_BEGIN + 150,
    
    MSG_ID_EMM_CODE_BEGIN, MSG_ID_EMM_CODE_TAIL = MSG_ID_EMM_CODE_BEGIN + 700,
    
    MSG_ID_EVAL_CODE_BEGIN, MSG_ID_EVAL_CODE_TAIL = MSG_ID_EVAL_CODE_BEGIN + 200,
    
    MSG_ID_ETC_CODE_BEGIN, MSG_ID_ETC_CODE_TAIL = MSG_ID_ETC_CODE_BEGIN + 150,
    
    MSG_ID_ESM_CODE_BEGIN, MSG_ID_ESM_CODE_TAIL = MSG_ID_ESM_CODE_BEGIN + 100,

    MSG_ID_HIF_MW_CODE_BEGIN, MSG_ID_HIF_MW_CODE_TAIL = MSG_ID_HIF_MW_CODE_BEGIN + 1500,
    
    MSG_ID_HIF_SVC_CODE_BEGIN, MSG_ID_HIF_SVC_CODE_TAIL = MSG_ID_HIF_SVC_CODE_BEGIN + 1000,

    MSG_ID_UPCM_CODE_BEGIN ,  MSG_ID_UPCM_CODE_TAIL = MSG_ID_UPCM_CODE_BEGIN+20,

    MSG_ID_PROXY_CODE_BEGIN, MSG_ID_PROXY_CODE_TAIL = MSG_ID_PROXY_CODE_BEGIN + 20,

    MSG_ID_LTECSR_CODE_BEGIN, MSG_ID_LTECSR_CODE_TAIL = MSG_ID_LTECSR_CODE_BEGIN + 50,

    MSG_ID_IMC_CODE_BEGIN, MSG_ID_IMC_CODE_TAIL = MSG_ID_IMC_CODE_BEGIN + 1000,

    MSG_ID_SDM_CODE_BEGIN, MSG_ID_SDM_CODE_TAIL = MSG_ID_SDM_CODE_BEGIN + 500,

    MSG_ID_VDM_CODE_BEGIN, MSG_ID_VDM_CODE_TAIL = MSG_ID_VDM_CODE_BEGIN + 1000,

    MSG_ID_IMCSMS_CODE_BEGIN, MSG_ID_IMCSMS_CODE_TAIL = MSG_ID_IMCSMS_CODE_BEGIN + 20,

    MSG_ID_IMSP_CODE_BEGIN, MSG_ID_IMSP_CODE_TAIL = MSG_ID_IMSP_CODE_BEGIN + 500,

    MSG_ID_AS_LOG_CODE_BEGIN, MSG_ID_AS_LOG_CODE_TAIL = MSG_ID_AS_LOG_CODE_BEGIN + 100,

    MSG_ID_LBS_CODE_BEGIN ,  MSG_ID_LBS_CODE_TAIL = MSG_ID_LBS_CODE_BEGIN + 20,

    MSG_ID_LPP_CODE_BEGIN, MSG_ID_LPP_CODE_TAIL = MSG_ID_LPP_CODE_BEGIN + 100,

    /* Reserved for CCCI, please should add mew MSG group before this line,reserve 64 for tool */
    MSG_ID_CCCI_MSG_CODE_BEGIN = 0xFF00, MSG_ID_CCCI_MSG_CODE_TAIL = MSG_ID_CCCI_MSG_CODE_BEGIN + 254 - 64,
    
    MSG_ID_CODE_END,  
    END_OF_MSG_ID_BEGIN = MSG_ID_CODE_END,
    END_OF_MSG_ID_TAIL = MSG_ID_CODE_END,
} MSG_ID_CODE_BEGIN;

#ifdef GEN_FOR_PC
    #define MODULE_MSG_BEGIN(BEGIN_POS)  typedef enum __cgen_msg_type_id_##BEGIN_POS{MSG_TAG_##BEGIN_POS = BEGIN_POS,
    #define MODULE_MSG_END(END_POS) MSG_ID_CGEN_PARSE_LAST_ID=END_POS }_cgen_msg_type_id_##END_POS;
#else
    #define MODULE_MSG_BEGIN(BEGIN_POS)   enum { MSG_TAG_##BEGIN_POS = BEGIN_POS,
    #define MODULE_MSG_END(END_POS)     };    
#endif /* GEN_FOR_PC */

/* user defined name */
#define CMUX_MSG_CODE_BEGIN                    MSG_ID_CMUX_CODE_BEGIN
#define DRIVER_MSG_CODE_BEGIN                  MSG_ID_DRIVER_CODE_BEGIN
#define FT_MSG_CODE_BEGIN                      MSG_ID_FT_CODE_BEGIN
#define L1_MSG_CODE_BEGIN                      MSG_ID_L1_CODE_BEGIN
#define TST_MSG_CODE_BEGIN                     MSG_ID_TST_CODE_BEGIN

MODULE_MSG_BEGIN(END_OF_MSG_ID_BEGIN)
    MSG_ID_END = END_OF_MSG_ID_BEGIN,
MODULE_MSG_END(END_OF_MSG_ID_TAIL)

#endif /* MODULE_MSG_RANGE_H */
