#ifndef MODULE_HISRID_RANGE_H
#define MODULE_HISRID_RANGE_H

typedef enum {
	HISR_ID_CODE_RESERVED = 0,    
	HISR_ID_SS_CODE_BEGIN = HISR_ID_CODE_RESERVED,
	HISR_ID_MODEM_CODE_BEGIN = HISR_ID_SS_CODE_BEGIN + 9,
	HISR_ID_DRV_CODE_BEGIN = HISR_ID_MODEM_CODE_BEGIN + 17,
	HISR_ID_LISR2HISR_CODE_BEGIN = HISR_ID_DRV_CODE_BEGIN + 22,
	HISR_ID_CODE_MAX = 9 + 17 + 22 + 61
} HISR_ID_CODE_BEGIN;


#endif /* MODULE_HISRID_RANGE_H */
